### ISSUE TITLE
Default chat input after closing pop-out chat

### ISSUE THREAD

**Issue by sc0ty** [Xzensi/NipahTV#113]
**Reproduction steps:**
1. Open pop-out chat
2. Close pop-out chat

When chat next to the video player reappears, default input box is shown.

**Comment by Xzensi** [comment]
Sadly due to Kick using a react framework it keeps destroying and re-creating all elements so any eventHandlers I attach for this get constantly destroyed as well so I'll have to add another eventHandler for the settings button etc. Alternatively just hiding the button with CSS wont be reliable due to Kick not using any unique classes or identifiers to allow this.

Considering theres a new website coming up soon I'll put this on ice until new website revamp launches.

**Comment by Xzensi** [comment]
No longer an issue
