### ISSUE TITLE
Inconsistent padding between chat messages when emote is present

### ISSUE THREAD

**Issue by bhdrozgn** [Xzensi/NipahTV#130]
~Emotes are looking bigger than usual and the padding between chat messages are too large.~

~Chat looks better after:~
- ~Changing `padding` attribute of `ntv__chat-message` class in `assets/SCSS/_messages.scss` from `0.33em 0.9em` to `0.25em 0.9em`~
- ~Changing `height` attribute of `img` tag of `ntv__inline-emote-box` class in `assets/SCSS/_emotes.scss` from `#{math.pow(1 + math.div(1, 3), 3)}em` to `#{math.pow(1 + math.div(1, 4), 3)}em`~

~Can you make these changes or at least give us a setting for customizing it?~

When a message in chat contains an emote, the padding between it and adjacent messages becomes larger. When a message does not contain an emote, the padding is normal. This causes the chat to look uneven and awkward. Can we have a fixed padding regardless of whether the message contains an emote or not?

**Comment by bhdrozgn** [comment]
After testing it more, I started to think that what I wrote was not the best solution for this problem.
Chat looks pretty good without emotes. The padding between chat messages is only big when there is a message with emotes.
7TV's behavior is to not change the padding between messages even if there is an emote, it doesn't care if emotes from different messages overlap. This makes the padding between messages always the same, giving a better look.

**Comment by Xzensi** [comment]
> 7TV's behavior is to not change the padding between messages even if there is an emote,  it doesn't care if emotes from different messages overlap.

Ah yeah I get what you mean, thats due to lineheight. I did consider this initially to make it equal to 7TV, but always thought it didn't look that good visually. But I agree that what it is now isn't entirely optimal either due to inconsistent lineheights as you mentioned. Simply forcing the lineheight to match the emote sizes, it would really space the lines way too far apart so that wouldn't be an option either. 

So I do believe that in the end it's indeed to better to just do what 7TV does and allow emotes to show "in front of eachother" by having them overlap with equal lineheight as the surrounding text.

I'm currently still fixing some pressing issues and bugs due to the Kick website update but I'll probably change this soon.

Thank you for your feedback!

**Comment by Xzensi** [comment]
Implemented this earlier than planned due to other related changes that had to happen anyway.

Added in 0e7743978e8a8d156a59b654e592755e2818a737
