### ISSUE TITLE
On kick, when people types long texts and have more lines, it hides the lower ones

### ISSUE THREAD

**Issue by RafaelCV** [Xzensi/NipahTV#147]
On kick, when people types long texts and have more lines on it to show, it hides the lower ones, then you need scroll down the text to can see it. Not happens every time, but happens so much. Seems happens even more when using 1 line on "Show quick emote holder"

**Comment by Xzensi** [comment]
This is sadly an unsolvable problem as it is currently right now. 

The issue is that Kick renders its messages, NTV hides them, re-renders them with all emotes and then shows them again. Regardless whether of NTV hides the messages or not, the messages will differ in size after the emotes have been rendered. But Kick already calculated the height of the messages before the emotes were rendered so the positions of the messages in the list are no longer correct.

The only way to fix this is to completely take over the chat with our own chat system, which I do am planning on to do, but takes a bit of time to work out and implement. I'd like to first get things a bit more stable before starting with that so people can be content with the current state while waiting for me to implement that, but that'd kind of be the next step anyway.
