### ISSUE TITLE
Nipah don't show the 7TV emotes from the channel, only the Hallowwen ones

### ISSUE THREAD

**Issue by RafaelCV** [Xzensi/NipahTV#190]
On Nipah:
https://i.imgur.com/erjPWgK.png

On 7TV itself it shows:
https://i.imgur.com/csYGvOH.png

**Comment by RafaelCV** [comment]
Oh, noticed it happens on firefox, on Chrome it shows.

**Comment by Xzensi** [comment]
Can confirm it loads fine for me on both emote sets as you shown in 7tv screenshot. I suspect it was just 7tv servers crapping out momentarily or something, can you confirm that it keeps happening even after refreshing page?

**Comment by Xzensi** [comment]
> Oh, noticed it happens on firefox, on Chrome it shows: https://i.imgur.com/eR44UVc.png

That happens when the 7TV CDN servers are slow to load the emote images, it just takes a little while to load. Sometimes when the CDN servers are really slow or just completely unresponsive it might give up trying to load some emote images. This does happen some days when load is particularily high for the CDN's. A simple refresh will have it retry to reload the emotes that failed to load (until it finally does load, unresponsive 7TV CDN servers are sadly out of my control).

**Comment by RafaelCV** [comment]
Refreshed many times, enabled, disabled, nipah, 7tv, etc doing many tests, always the same, aways refreshing the page, always same with Nipah, on chrome it worked fine.

**Comment by Xzensi** [comment]
That's strange, can you confirm it happens on other channels as well, just on your Firefox? Are you using the add-on or userscript?

**Comment by RafaelCV** [comment]
I only follow one channel, don't know other with 7tv emotes i can test, using the addon

**Comment by RafaelCV** [comment]
And yes, seems only happen on my firefox, even trying ctrl+F5 to refresh the cache.

**Comment by Xzensi** [comment]
Any channel is fine, the point is just to check if the emote sets shown in 7TV extension show up in NTV as well. Can you test these channels as well and see if all emote sets show up?

https://kick.com/xqc
https://kick.com/roshtein

Both of these channels have a 7TV channel + 7TV global emote set alongside a Kick channel + Kick global emote set.

**Comment by RafaelCV** [comment]
Ok, those only followers, and only gonna open chat to me after 10 minutes, followed and gonna test after it's time

**Comment by RafaelCV** [comment]
Same happened on both: 
https://i.imgur.com/btC3fWq.png
https://i.imgur.com/u2NPfsL.png

Only Halloween ones.

**Comment by RafaelCV** [comment]
Rosh's one only partially loaded at 1st time, but even after refresg, fomr 7tv only Halloween ones:
https://i.imgur.com/uyXeJAR.png

**Comment by Xzensi** [comment]
I assume you're on latest version 1.5.54. I'm thinking it's 7TV currently having issues because NTV just simply shows what 7TV's servers provides, they're currently still rolling up issues after a big backend migration. What I don't get though, is why it does work for you in Chrome but not in Firefox even after clearing cache.

Could you maybe join the [NipahTV Discord community server](https://discord.com/invite/u2gEQZrB6h)? It's easier to talk there than posting here, there's some logs I'd like to see if possible. Other than that I think it's best to just wait for a day and give it a little bit of time to see if they fix it, because it's most likely just a bug on 7TV's end.

**Comment by Xzensi** [comment]
Resolved over Discord, issue was corrupt or stale cookies causing 7TV to throw "unauthorized" errors when loading channel emote set.
