### ISSUE TITLE
spaces in messages being ommited in kick chat using firefox

### ISSUE THREAD

**Issue by elderddragon** [Xzensi/NipahTV#27]
When I enable the script on Kick my chat doesn't show spaces between words for everyone that's chatting. Itwouldlooksomethinglikethis. 

I'm on Firefox, using Violentmonkey as the script manager, and installed from URL as per the instructions here.

**Comment by Xzensi** [comment]
That was a bug introduced in a merge of version 1.3.1 which made some big changes to how emotes and text got rendered. One of which was the complete removal of extra adding of padding spaces. This was implemented in a different way where spaces are no longer needed, however the merge got messed up and was fixed in hotfix version 1.3.3.

Can you please make sure you're on lastest version? As of writing the latest version is currently 1.3.5. Violentmonkey by default only updates once a day.

**Comment by Xzensi** [comment]
If you're not sure how to manually update the script, click this button:

![image](https://github.com/Xzensi/NipahTV/assets/14015478/f1dcdb35-559f-4d63-9e37-f45a0488baaf)

**Comment by elderddragon** [comment]
I was having this problem for a few days, but yes, manually updating solved it. 

Thanks for the reply, I'll keep a closer eye on updates now.

**Comment by Xzensi** [comment]
Sounds like it just wasn't able to update the script for whatever timing reason. It's a bit of a bummer I can't really broadcast or announce important updates or hotfixes to inform people to update when versions are known to have breaking bugs when it's installed as an userscript. I do plan on likely packaging NipahTV as browser extension later though so then it wouldn't be an issue anymore.

Saying this now did give me some ideas of maybe having it periodically check against some table on github that might be able to serve as broadcasting mechanism though to inform people to manually update. I'll look into this.
